apiVersion: v2
name: helm-chart
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
- name: tcp-server
  version: "0.1.0"
  repository: "file://charts/playground-tcp"
- name: udp-server
  version: "0.1.0"
  repository: "file://charts/playground-udp"
- name: logger
  version: "0.1.0"
  repository: "file://charts/playground-logger"
- name: eck-operator
  version: "2.11.1"
  repository: "https://helm.elastic.co"
- name: kafka
  version: "26.8.5"
  repository: "https://charts.bitnami.com/bitnami"
- name: cadvisor
  version: "2.3.1"
  repository: "https://ckotzbauer.github.io/helm-charts"
- name: memcached
  version: "6.11.1"
  repository: "https://charts.bitnami.com/bitnami"
- name: kube-prometheus-stack
  version: "56.6.2"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: prometheus-adapter
  version: "4.9.0"
  repository: "https://prometheus-community.github.io/helm-charts"