version: '3'


networks:
  playground:
    name: "ps"
    external: "true"

services:
  envoy:
    hostname: envoy
    networks:
      - playground
    image: envoyproxy/envoy:dev-b79d9f17bb6f9e42c6ce3fabd1570a43dceaaa69
    ports:
      - "20000:20000"
      - "10000:10000"
      - "10001:10001/udp"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml