      admin:
        address:
          socket_address:
            address: 0.0.0.0
            port_value:  20000
      static_resources:
        listeners:
          - name: tcp_listener
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 10000
                protocol: TCP
            filter_chains:
              - filters:
                  - name: envoy.filters.network.tcp_proxy
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                      stat_prefix: tcp-service
                      cluster: service_tcp
                      access_log:
                        - name: envoy.access_loggers.stdout
                          typed_config:
                            "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          - name: udp_listener
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 10001
                protocol: UDP
            listener_filters:
            - name: envoy.filters.udp_listener.udp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
                stat_prefix: udp-service
                matcher:
                  on_no_match:
                    action:
                      name: route
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                        cluster: service_udp
        clusters:
          - name: service_tcp
            lb_policy: LEAST_REQUEST
            type: STRICT_DNS
            circuit_breakers:
              thresholds:
                max_connections: 50000
                max_pending_requests: 50000
                max_requests: 50000
            connect_timeout: 30s
            dns_lookup_family: V4_ONLY
            load_assignment:
              cluster_name: service_tcp
              endpoints:
                - lb_endpoints:
                    - endpoint:
                        address:
                          socket_address:
                            address: tcp-server
                            port_value: 40000
          - name: service_udp
            lb_policy: LEAST_REQUEST
            type: STRICT_DNS
            circuit_breakers:
              thresholds:
                max_connections: 50000
                max_pending_requests: 50000
                max_requests: 50000
            load_assignment:
              cluster_name: service_udp
              endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: udp-server
                        port_value:  50000