apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "playground-logger.fullname" . }}-sa'
  labels:
    {{- include "playground-logger.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
  - name: {{ printf "%s-kafka-user-passwords" .Release.Name }}
automountServiceAccountToken: true
