# Default values for playground-tcp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kafkaLogsTopic: ""
kafkaUser: ""
kafkaPassword: ""
elasticsearchUsername: ""
elasticsearchPassword: ""
elasticsearchPort: 9200
kafkaPort: 9092


podLabels:
  app: logger
  version: v1

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

serviceAccount:
  annotations:
    kubernetes.io/enforce-mountable-secrets: 'true'

nameOverride: ""
fullnameOverride: ""
resources: {}
podAnnotations: {}
podSecurityContext: {}
