# using 172.23.0.2 as self ip addr

version: '2'
networks:
  playground:
    name: "ps"
    external: "true"

services:
  kafka:
    hostname: kafka
    networks:
      - playground
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://kafka:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:SASL_PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://kafka:9092
      - KAFKA_CLIENT_USERS=user
      - KAFKA_CLIENT_PASSWORDS=password
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
      - KAFKA_CONTROLLER_USER=controller_user
      - KAFKA_CONTROLLER_PASSWORD=controller_password
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_PLAINTEXT
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_INTER_BROKER_USER=controller_user
      - KAFKA_INTER_BROKER_PASSWORD=controller_password
      - KAFKA_CERTIFICATE_PASSWORD=password
      - KAFKA_TLS_TYPE=JKS # or PEM
    volumes:
      - '../../certs/kafka/kafka.truststore.jks:/bitnami/kafka/config/certs/kafka.truststore.jks'
      - '../../certs/kafka/kafka.keystore.jks:/bitnami/kafka/config/certs/kafka.keystore.jks'
  memcached:
    hostname: memcached
    networks:
      - playground
    image: 'memcached:latest'
    ports:
      - '11211:11211'
  # udp-server:
  #   restart: on-failure
  #   depends_on:
  #     - memcached
  #   networks:
  #     - playground
  #   image: 'udp-server:1.0.3'
  #   ports:
  #     - '50000:50000/udp'
  #   command: ["dumb-init", "/usr/src/server/dist"]
  # tcp-server:
  #   restart: on-failure
  #   depends_on:
  #     - kafka
  #     - memcached
  #   networks:
  #     - playground
  #   image: 'tcp-server:1.0.3'
  #   ports:
  #     - '40000:40000'
  #   command: ["dumb-init", "/usr/src/server/dist"]
  #   environment:
  #     - KAFKA_BROKERS=kafka:9092
  #     - MEMCACHED=memcached:11211