apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "playground-udp.fullname" . }}-sa'
  labels:
    {{- include "playground-udp.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
