# using 172.23.0.2 as self ip addr

version: '2'
networks:
  playground:
    name: "ps"
    external: "true"

services:
  udp-server:
    restart: on-failure
    hostname: udp-server
    # depends_on:
    #   - memcached
    networks:
      - playground
    image: 'udp-server:1.0.1'
    ports:
      - '50000:50000/udp'
    command: ["/dist"]
    environment:
      - KAFKA_BROKERS=kafka:9092
      - MEMCACHED_SERVICE=memcached
      - MEMCACHED_PORT=11211
  tcp-server:
    restart: on-failure
    hostname: tcp-server
    # depends_on:
    #   - kafka
    #   - memcached
    networks:
      - playground
    image: 'tcp-server:1.0.1'
    ports:
      - '40000:40000'
    command: ["/dist"]
    environment:
      - KAFKA_BROKERS=kafka:9092
      - MEMCACHED_SERVICE=memcached
      - MEMCACHED_PORT=11211